name: Build and Push Docker image

on:
  push:
    branches:
      - main  # se ejecuta en cada push a main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USER }}/miappnode:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USER }}/miappnode:latest
